[package]
name = "off_rs"
version = "0.1.0"
edition = "2021"
authors = ["Michael Lohr <michael@lohr.dev>"]
keywords = ["off", "3d", "format", "mesh"]
description = "A library for parsing .off mesh files"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/michidk/off_rs"
homepage = "https://github.com/michidk/off_rs"

[lib]
name = "off_rs"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.30"
